### PR TITLE
# Dancing Headers

### PR DESCRIPTION
**Pull request by DarkJaguar91**
* Corrected hasStickyHeader method to check for the top view since it is not always at position 0 in the Recyclerview's children list.
* Moved method into HeaderPositionCalculator
* Added a update button to the sample code since calling notifyItemUpdated seems to be the cause of the "Dance"

### CODE REVIEW

**Comment by DarkJaguar91** [comment]
Realised now i made the pull request to the incorrect branch...

**Comment by jacobtabak** [comment]
Thanks! I'm noticing some weirdness with the sample - the colors kind of glitch out when you click the update button. Looking into it now.

**Comment by jacobtabak** [comment]
Oh, I guess it's just the item animator.

**Comment by jacobtabak** [comment]
Merging, thanks!!!

**Pull request merged**
